#!/bin/bash
export LDFLAGS="-lgloss"
export RISCV=$(dirname $(realpath $0))

cat <<EOF > riscv64-unknown-elf/bin/riscv64-unknown-elf-wrapper
#!/bin/bash
exec "\$(basename \${0/riscv64-unknown-elf/${PREFIX:=riscv-sifive-elf}})" \$@
EOF

